--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HmmHmmmm/MailPlugin
build-by-default: true
branches:
- master
projects:
  BankUiPlugin:
    path: ""
    icon: "images/icon.png"
    libs:
    - src: NightLife/bank/BankUiPlugin
      version: ^1.0.1
      api: 3.11.7
...
